# Generated by Django 6.0.3 on 2026-03-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("isbn", models.CharField(max_length=20, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("year", models.IntegerField()),
                ("total_copies", models.IntegerField(default=1)),
                ("available_copies", models.IntegerField(default=1)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                ("description", models.TextField(blank=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
