# Generated by Django 6.0.3 on 2026-04-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="member_id",
            field=models.CharField(
                blank=True, default=None, max_length=20, null=True, unique=True
            ),
        ),
    ]
